#Iniciar os Containers do docker(Pode demorar um pouco na primeira vez):
#docker-compose up -d

#Pausar o Docker:
#docker-compose down

#Pausar o Docker para atualização de versão do banco de db_siged:
#docker-compose down -v

#Reconstruir Docker
#docker-compose up -d --build --force-recreate --no-deps

version: '3.8'
networks:
  banco:
  web:
volumes:
  db_stockcar:
services:
  www:
    build: ./docker/images/www/
    mem_limit: 1024M
    mem_reservation: 512M
    cpus: 1
    restart: always
    ports: 
      - "5566:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - web
      - banco
  db:
    build: ./docker/images/mysql/
    mem_limit: 1024M
    mem_reservation: 512M
    cpus: 1
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode="" 
    ports: 
      - "33:3355"
    expose: 
      - "3355"
    environment:
      MYSQL_DATABASE: budaweb_stockcar
      MYSQL_USER: budaweb_stockcar
      MYSQL_PASSWORD: key!stockcar
      MYSQL_ROOT_PASSWORD: key!stockcar
      MYSQL_TCP_PORT: 3355
      TZ: America/Bahia
    volumes:
      - ./docker/dump/stock_car.sql:/docker-entrypoint-initdb.d/init.sql
      - db_stockcar:/var/lib/mysql
    networks:
      - banco
  phpmyadmin:
    build: ./docker/images/phpmyadmin/
    mem_limit: 1024M
    mem_reservation: 512M
    cpus: 1
    restart: always
    ports: 
      - "5567:80"
    environment:
      MYSQL_USER: budaweb_stockcar
      MYSQL_PASSWORD: key!stockcar
      MYSQL_ROOT_PASSWORD: key!stockcar
      PMA_HOST: db
      PMA_PORT: 3355
    depends_on:
      - db
    networks:
      - banco
      - web